name:                json-to-haskell
version:             0.1.0.0
github:              "ChrisPenner/json-to-haskell"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "2020 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/json-to-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- aeson
- aeson-extra
- containers
- unordered-containers
- text
- mtl
- casing
- nonempty-containers
- bimap
- microlens-platform
- vector

ghc-options:
- -Wall

library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-patterns

executables:
  json-to-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-to-haskell
    - raw-strings-qq
    - optparse-applicative
    - bytestring
    - ansi-wl-pprint

tests:
  json-to-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-to-haskell
    - hspec
    - text
    - bytestring
    - raw-strings-qq
